### ISSUE TITLE
influxdb2 吞吐量计算错误

### ISSUE THREAD

**Issue by xinzhongtianxia** [thulab/iot-benchmark#186]
![image](https://user-images.githubusercontent.com/16996964/131099504-5f76482a-20fc-4ea6-8a2c-4530e2c2b9d0.png)
这里的循环是否应该去掉？

否则测出来的结果相差sensorNum倍

**Comment by stormbroken** [comment]
是的，这里有一些问题，我来进行相关的修改，align data是指只有某列sensor的数据

**Comment by stormbroken** [comment]
修复PR：#188
