### ISSUE TITLE
Please consider using Connection Pool when interacting with TSDBs

### ISSUE THREAD

**Issue by ytyou** [thulab/iot-benchmark#203]
Would you please consider using connection pool (e.g. `org.apache.http.impl.conn.PoolingHttpClientConnectionManager`) when sending requests to TSDBs (e.g. OpenTSDB)? Making a new HTTP connection whenever you need to send a request is not only inefficient, it also produces wrong results when system limits are reached. For example, we ran into TIME_WAIT port exhaustion problems when running the benchmark. When such limits are hit, benchmark results are no longer valid. Thanks!

**Comment by stormbroken** [comment]
Ok, We get this problem. We will check and fix it! Thanks for you suggestions.

**Comment by ZhenChen008** [comment]
> Ok, We get this problem. We will check and fix it! Thanks for you suggestions.

Hello, what is the connection pool used by infludb in this project? Could you please tell me the name ,THX!

**Comment by ytyou** [comment]
I'm taking this request back. Now that I think about it, each client should have its own (persistent) connection. That would resemble real use cases better than connection pools. I'm closing this. Thank you.
