### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by 2507110556** [thulab/iot-benchmark#340]
我按照readme里面的步骤做下来，然后执行benchmark.sh的时候一直报class not found该怎么解决啊

**Comment by SpriCoder** [comment]
这个是因为需要修改config文件的DB_SWITCH到对应的版本才能继续测试

**Comment by 2507110556** [comment]
> 这个是因为需要修改config文件的DB_SWITCH到对应的版本才能继续测试

谢谢您的回答，我发现我的问题了，我是package后才修改参数的，然后我在influxdb相关目录下操作，报找不到iotdb相关的类，我就很郁闷，想着配置文件为什么不生效，原来要先配置再打包（不太懂这个原理哈哈，谢谢您
