### ISSUE TITLE
[CHORE] iot-benmark uses a lot of cpu cores

### ISSUE THREAD

**Issue by Subsegment** [thulab/iot-benchmark#397]
# Description
After I implemented Iot-benchmark support for CnosDB, I found that the iot-benmark itself had a very high cpu usage during testing.But in fact, the concurrency is not much, CnosDB itself has a relatively low CPU usage, is this my implementation problem?

![Screenshot 2024-01-10 at 16 18 27](https://github.com/thulab/iot-benchmark/assets/74497693/2b7b97de-1176-484f-8f3d-b73ca23479f2)

I also tested Influxdb and found a similar one for iot-benchmark-influxdb

![Screenshot 2024-01-10 at 16 17 07](https://github.com/thulab/iot-benchmark/assets/74497693/28adbbaf-2cb7-4537-b17b-402cf3a8983d)

But when I tested iotdb, there was no problem with high cpu usage. Why？

![Screenshot 2024-01-10 at 16 15 59](https://github.com/thulab/iot-benchmark/assets/74497693/93b4b486-0c99-46d2-937e-65b4463605e4)

# Config
here is my config

```
BENCHMARK_WORK_MODE=verificationWriteMode

FILE_PATH=/path/to/data
DEVICE_NUMBER=50
SENSOR_NUMBER=10
CLIENT_NUMBER=50
BATCH_SIZE_PER_WRITE=10000
OPERATION_PROPORTION=1:0:0:0:0:0:0:0:0:0:0
BIG_BATCH_SIZE=10
IS_COPY_MODE=true
```

**Comment by liyuheng55555** [comment]
Perhaps you can use sampling tool (such as jprofile or arthas) to find out what function takes so much cpu when testing cnosdb and influxdb.

**Comment by OneSizeFitsQuorum** [comment]
You can use the `testWithDefaultPath` pattern directly, where `verificationWriteMode` checks the correctness of all data written, which is not needed for normal performance tests and can be CPU-expensive
