### ISSUE TITLE
java.lang.ClassNotFoundException: cn.edu.tsinghua.iot.benchmark.tdengine3.TDengine

### ISSUE THREAD

**Issue by xiaoyuanyaun1020** [thulab/iot-benchmark#408]
java.lang.ClassNotFoundException: cn.edu.tsinghua.iot.benchmark.tdengine3.TDengine

**Comment by SpriCoder** [comment]
I think you need to use the correct package to test. Firstly, you need to compile `tdengine-3.0` package and run test under the target in `tdengine-3.0` package
